name: vaura
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  remixicon: 
  http: ^1.4.0
  path_provider: ^2.1.5
  url_launcher:
  app_links: ^3.3.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding_ai.svg
    - assets/onboarding_chat.svg
    - assets/onboarding_security.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Use your high-res icon (1024×1024 ideally)
  remove_alpha_ios: true         # Removes transparency (required by App Store)